### ISSUE TITLE
Make everybody's lives easier

### ISSUE THREAD

**Issue by shayypy** [DraxxisGH/DraxVRPack#6]
1. Upload the files to the GH repo and put an export zip on the /releases page
2. Make sure the pack actually works with vivecraft -- VR mode vivecraft, not 2D -- before continuing development or else you'll have to do a **lot** of troubleshooting

**Comment by shayypy** [comment]
You absolute dumb cretin @DraxxisGH

**Comment by DraxxisGH** [comment]
da strangest ting is nobody assed

**Comment by shayypy** [comment]
i will be here when the pack does not work then
